version: 1.0.{build}
image: visual studio 2017
init: 
  - ps: Set-ItemProperty -Path HKLM:\SYSTEM\CurrentControlSet\Control\FileSystem -Name LongPathsEnabled -Value 1
  - git config --system core.longpaths true
clone_script:
  - git clone -c core.longpaths=true -q --branch=master https://github.com/OwenMcDonnell/NetCoreAppTest.git C:\projects\netcoreapptest
install:
  #- ps: Set-ItemProperty -Path HKLM:\SYSTEM\CurrentControlSet\Control\FileSystem -Name LongPathsEnabled -Value 1
  #- git config --system core.longpaths true
#- ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
before_build:
- ps: >- 
    Install-Product node $Env:nodejs_version

    npm install -g npm

    npm install -g webpack

    npm install -g webpack-cli

    cd %APPVEYOR_BUILD_FOLDER%
build_script:
- pwsh: ./build.ps1
#- pwsh: >-
 #   $ErrorActionPreference = "Stop"
#
 #   dotnet build

  #  $?

   # $lastexitcode
