version: 1.0.{build}
image: visual studio 2017
init: 
  - ps: Set-ItemProperty -Path HKLM:\SYSTEM\CurrentControlSet\Control\FileSystem -Name LongPathsEnabled -Value 1
  - git config --system core.longpaths true
install:
  #- ps: Set-ItemProperty -Path HKLM:\SYSTEM\CurrentControlSet\Control\FileSystem -Name LongPathsEnabled -Value 1
  #- git config --system core.longpaths true
#- ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
build_script:
- pwsh: ./build.ps1
#- pwsh: >-
 #   $ErrorActionPreference = "Stop"
#
 #   dotnet build

  #  $?

   # $lastexitcode
